"""add lead review tracking

Revision ID: 3f591bc1ebd4
Revises: 1ee69dbff242
Create Date: 2026-10-03 10:33:09.634835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f591bc1ebd4'
down_revision: Union[str, Sequence[str], None] = '1ee69dbff242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "leads",
        sa.Column(
            "reviewed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "leads",
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'reviewed_at')
    op.drop_column('leads', 'reviewed')
    # ### end Alembic commands ###
