"""add lead next action

Revision ID: 9cd6bdc0e901
Revises: 1627da9a6dd3
Create Date: 2026-10-04 16:46:34.143095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd6bdc0e901'
down_revision: Union[str, Sequence[str], None] = '1627da9a6dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('next_action', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'next_action_at')
    op.drop_column('leads', 'next_action')
    # ### end Alembic commands ###
